# Generated by Django 4.1.4 on 2022-12-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_service_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
