# Generated by Django 4.1.4 on 2022-12-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_address_shop_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='gyug'),
            preserve_default=False,
        ),
    ]
