# Generated by Django 4.1.4 on 2022-12-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
