# Generated by Django 4.1.4 on 2022-12-11 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_service_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
