# Generated by Django 4.1.4 on 2022-12-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_appointment_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
    ]
