# Generated by Django 4.1.4 on 2022-12-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_appointment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='asdvfasedv sadvasdfv'),
            preserve_default=False,
        ),
    ]
